version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/personal-finance-tracker
      - JWT_SECRET=assessment_secret_key_12345
      - PORT=5000
    depends_on:
      - mongo
    volumes:
      - ./backend:/app

volumes:
  mongo_data:
